Deprecated v1 vault and total supply endpoints
UmamiDAO/metrics-api pull request #49
Opened 2022-12-22 23:51 UTC by Clonescody

Closes #23 

Adds back 2 routes to support the v1 deprecated vault on the legacy UI

- `v1/vault/balance` => returns the current balance deposited
- `v1/vault/cap` => returns the max deposit cap, hardcoded to 5500000000000 as per the [previous implementation](https://github.com/UmamiDAO/metrics-api/blob/515a4d06a59e8851ea7f64d986202fc4d2d5a34b/libs/withdraw.js#L38)

Add a route to return the current total supply for CMC

- `v2/token/totalSupply` => returns supply minus forever locked tokens

2022-12-23 16:31 UTC, gpxl-dev commented on api/controllers/dep-vault/dep-vault.dao.ts
> +    let pending = await vault.totalPending();
`totalPending` seems to be one of the properties of `vaultState` - you may not need to make this call.

2022-12-23 16:33 UTC, gpxl-dev requested changes

2022-12-23 16:33 UTC, gpxl-dev commented on api/controllers/token/token.controller.ts
> +        parseFloat(tokenMetrics.totalSupply) - parseFloat(tokenMetrics.foreverLocked),
As discussed let's change this to not exclude the locked tokens for consistency w/ the UI and etherscan etc.

2022-12-28 15:38 UTC, Clonescody commented on api/controllers/token/token.controller.ts
> +        parseFloat(tokenMetrics.totalSupply) - parseFloat(tokenMetrics.foreverLocked),
Kept like this to match both CMC and CG's guidelines, as we have the breakdown on the site it's less of an issue.

2022-12-28 15:41 UTC, merged